version: '3'

services:
    db:
        image: mariadb
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: Welkom01!
    fpm:
        build: .docker/fpm/.
        volumes: 
            - '.:/var/www'
        links:
            - db
    web:
        image: nginx
        volumes:
            - '.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - '.:/var/www'
        ports:
            - '80:80'
        links: 
            - fpm